server:
  port: 8080

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse_rental?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=TRUE
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 21092002
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      format_sql: true
      jdbc:
        time_zone: ${DB_TIME_ZONE:Asia/Ho_Chi_Minh}
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: datbthe170585@fpt.edu.vn
    password: huqzcosekirojfub
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  expiration: 2592000
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=


